var namespace_college_quiz_web_1_1_a_p_i_1_1_services_1_1_quiz_session =
[
    [ "IQuizSessionAPIService", "interface_college_quiz_web_1_1_a_p_i_1_1_services_1_1_quiz_session_1_1_i_quiz_session_a_p_i_service.html", "interface_college_quiz_web_1_1_a_p_i_1_1_services_1_1_quiz_session_1_1_i_quiz_session_a_p_i_service" ],
    [ "QuizSessionAPIService", "class_college_quiz_web_1_1_a_p_i_1_1_services_1_1_quiz_session_1_1_quiz_session_a_p_i_service.html", "class_college_quiz_web_1_1_a_p_i_1_1_services_1_1_quiz_session_1_1_quiz_session_a_p_i_service" ]
];