var namespace_college_quiz_web_1_1_services_1_1_shared_quizes_service =
[
    [ "ISharedQuizesService", "interface_college_quiz_web_1_1_services_1_1_shared_quizes_service_1_1_i_shared_quizes_service.html", "interface_college_quiz_web_1_1_services_1_1_shared_quizes_service_1_1_i_shared_quizes_service" ],
    [ "SharedQuizesService", "class_college_quiz_web_1_1_services_1_1_shared_quizes_service_1_1_shared_quizes_service.html", "class_college_quiz_web_1_1_services_1_1_shared_quizes_service_1_1_shared_quizes_service" ]
];